### ISSUE TITLE
Pass space width as an argument

### ISSUE THREAD

**Issue by ghost** [pointfreeco/swift-enum-properties#10]
Hi,

Please consider adopting Xcode's default Tab Width of 4 spaces, or, if possible, and as an alternative, the ability to pass the width as an argument. 

```sh
./generate-enum-properties --tab-width 4
```

This would allow me to use `generate-enum-properties` in the build phase, without having to manually `Ctrl + I` the files in question.

Thank you 🙏

**Comment by ghost** [comment]
I have a feeling that this request may be stretching the scope of swift-enum-properties, and I should be using something like swift-format in my build phases 🤔

**Comment by ghost** [comment]
And that I shouldn't be using `swift-enum-properties` in a build phase 🔨 🤔 

Well, this was helpful!

**Comment by ghost** [comment]
Oh, and your videos are awesome! 💯

**Comment by stephencelis** [comment]
We try do a very naive detection of the current indentation in a file: https://github.com/pointfreeco/swift-enum-properties/blob/master/Sources/EnumProperties/EnumPropertyRewriter.swift#L40

Not sure if it's failing for you or just the fact that Xcode indentation is different, but yeah, your best bet is something like `swift-format`.
